# Generated by Django 3.2 on 2021-05-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamaRw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_rw', models.CharField(max_length=50)),
                ('nama_ketua_rw', models.CharField(max_length=50)),
                ('alamat_rw', models.CharField(max_length=100)),
                ('hp_ketua_rw', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nama rw',
                'verbose_name_plural': 'Nama rw',
            },
        ),
    ]
