# Generated by Django 3.2 on 2021-05-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desa', '0001_initial'),
        ('rt', '0001_initial'),
        ('rw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(help_text='Boleh dikosongkan.', max_length=100)),
                ('nama_panggilan', models.CharField(help_text='Boleh dikosongkan.', max_length=30)),
                ('nik', models.CharField(help_text='Boleh dikosongkan.', max_length=20)),
                ('hp', models.CharField(help_text='Boleh dikosongkan.', max_length=20, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki'), ('P', 'Perem')], help_text='Klik tanda panah.', max_length=10)),
                ('tempat_lahir', models.CharField(help_text='Contoh: Denpasar, Bali atau Boleh dikosongkan.', max_length=50, null=True)),
                ('tanggal_lahir', models.CharField(help_text='Contoh: 01/01/2001 atau Boleh dikosongkan.', max_length=12, null=True)),
                ('agama', models.CharField(choices=[('Isl', 'Islam'), ('Kris', 'Kristen'), ('Kat', 'Katolik'), ('Hin', 'Hindu'), ('Kong', 'Konghucu')], help_text='Klik tanda panah.', max_length=10)),
                ('pend_tertinggi', models.CharField(choices=[('-', 'Tidak diketahui'), ('SD', 'SD'), ('SMP/SETARA', 'SMP/SETARA'), ('SMU/SETARA', 'SMU/SETARA'), ('SMK', 'SMK'), ('S1', 'S1'), ('S2', 'S2'), ('DR', 'DR'), ('PROP', 'Prof')], help_text='Klik tanda panah.', max_length=10)),
                ('status_perkawinan', models.CharField(choices=[('BM', 'Belum menikah'), ('SM', 'Menikah'), ('JD', 'Janda'), ('DD', 'Duda')], help_text='Klik tanda panah.', max_length=10)),
                ('status_hub_dlm_kel', models.CharField(choices=[('KK', 'Kepala Keluarga'), ('SU', 'Suami'), ('IS', 'Istri'), ('AK', 'Anak Kandung'), ('AA', 'Anak Angkat'), ('AI', 'Anak Tiri')], help_text='Klik tanda panah.', max_length=30)),
                ('nama_ibu', models.CharField(help_text='Boleh dikosongkan.', max_length=50, null=True)),
                ('nama_ayah', models.CharField(help_text='Boleh dikosongkan.', max_length=50, null=True)),
                ('alamat_tempat_tinggal', models.CharField(help_text='Tidak boleh dikosongkan.', max_length=100)),
                ('kondisi_kesehatan', models.CharField(choices=[('B', 'Baik'), ('KB', 'Kurang baik')], help_text='Klik tanda panah.', max_length=30)),
                ('penyakit_khusus', models.CharField(choices=[('JTG', 'Jantung'), ('DIABET', 'Diabet'), ('ASMA', 'Asma'), ('PARU', 'Paru'), ('HIV', 'Hiv'), ('GJAL', 'Ginjal'), ('TA', 'Tidak ada')], help_text='Klik tanda panah.', max_length=30)),
                ('covid', models.CharField(choices=[('TIDAK TERPAPAR', 'Tidak'), ('TERPAPAR COVID-19', 'Terpapar Covid-19'), ('TERPAPAR VARIAN BARU', 'Terpapar varian baru')], help_text='Klik tanda panah.', max_length=30)),
                ('waktu_terpapar', models.CharField(help_text='Contoh: 01/05/2021', max_length=30)),
                ('gejala_saat_terpapar', models.TextField(help_text='Boleh dikosongkan.', null=True)),
                ('status', models.CharField(choices=[('ISOLASI', 'Isolasi mandiri'), ('DIRAWAT', 'Dirawat di RS'), ('PULIH', 'Pulih normal'), ('TDK TERPAPAR', '-')], help_text='Klik tanda panah.', max_length=30)),
                ('profesi', models.CharField(choices=[('Pemulung', 'Pemulung'), ('Tukang', 'Tukang'), ('Ojek', 'Ojek'), ('Sopir', 'Sopir'), ('Petani', 'Petani'), ('K5', 'K5'), ('Pedagang Warung', 'Pedagang warung'), ('AST', 'AST'), ('ASN', 'ASN'), ('AMN', 'AMN'), ('Polisi', 'Polisi'), ('Guru', 'Guru'), ('Dosen', 'Dosen'), ('Profesional', 'Profesional'), ('Wira Swasta', 'Wira Swasta'), ('Pensiunan', 'Pensiunan'), ('Honorer', 'Honorer'), ('Lain Lain', 'Lain lain')], help_text='Klik tanda panah.', max_length=30)),
                ('penghasilan_per_bulan', models.CharField(choices=[('Kurang 1 Juta', 'Kurang 1 juta'), ('Sampai 1,5 Juta', 'Sampai 1,5 juta'), ('Kurang dari 2 Juta', 'Kurang dari 2 juta'), ('Kurang dari 2,5 Juta', 'Kurang dari 2,5 juta'), ('Kurang dari 3 Juta', 'Kurang dari 3 juta'), ('Kurang dari 3,5 Juta', 'Kurang dari 3,5 juta'), ('Kurang dari 4 Juta', 'Kurang dari 4 juta'), ('Kurang dari 5 Juta', 'Kurang dari 5 juta'), ('Kurang dri 7 Juta', 'Kurang dri 7 juta'), ('Kurang dari 10 Juta', 'Kurang dari 10 juta'), ('Lebih dari 10 Juta', 'Lebih dari 10 juta')], help_text='Klik tanda panah.', max_length=30)),
                ('jumlah_anggota_keluarga', models.CharField(choices=[('1 Orang', '1 orang'), ('2 Orang', '2 orang'), ('3 Orang', '3 orang'), ('4 Orang', '4 orang'), ('5 Orang', '5 orang'), ('6 Orang', '6 orang'), ('7 Orang', '7 orang'), ('8 Orang', '8 orang'), ('9 Orang', '9 orang'), ('10 Orang', '10 orang'), ('Lebih Dari 10 Orang', 'Lebih Dari 10 orang')], help_text='Klik tanda panah.', max_length=30)),
                ('jenis_rumah_tempat_tingal', models.CharField(choices=[('Petakan Lantai Tanah', 'Petakan Lantai Tanah'), ('Petakan Lantai Semen', 'Petakan Lantai Semen'), ('Petakan Lantai Keramik', 'Petakan Lantai Keramik'), ('Rumah Semi Permanen', 'Rumah Semi Permanen'), ('Rumah Permanen', 'Rumah Permanen')], help_text='Klik tanda panah.', max_length=30)),
                ('status_rumah_tempat_tinggal', models.CharField(choices=[('Sewa', 'Sewa'), ('Milik Orang Tua', 'Milik Orang Tua'), ('Milik Sendiri', 'Milik Sendiri')], help_text='Klik tanda panah.', max_length=30)),
                ('desa', models.ForeignKey(help_text='Klik tanda panah.', on_delete=django.db.models.deletion.CASCADE, to='desa.desa')),
                ('rt', models.ForeignKey(help_text='Klik tanda panah.', on_delete=django.db.models.deletion.CASCADE, to='rt.rukuntetangga')),
                ('rw', models.ForeignKey(help_text='Klik tanda panah.', on_delete=django.db.models.deletion.CASCADE, to='rw.rukunwarga')),
            ],
            options={
                'verbose_name': 'Warga',
                'verbose_name_plural': 'Warga',
            },
        ),
    ]
