# Generated by Django 3.2 on 2021-05-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rt', '0001_initial'),
        ('desa', '0001_initial'),
        ('wna', '0001_initial'),
        ('rw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nama_panggilan', models.CharField(max_length=30)),
                ('nik', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki'), ('P', 'Perem')], max_length=10)),
                ('tempat_lahir', models.CharField(max_length=50, null=True)),
                ('agama', models.CharField(choices=[('Isl', 'Islam'), ('Kris', 'Kristen'), ('Kat', 'Katolik'), ('Hin', 'Hindu'), ('Kong', 'Konghucu')], max_length=10)),
                ('pend_tertinggi', models.CharField(choices=[('-', 'Tidak diketahui'), ('SD', 'SD'), ('SMP/SETARA', 'SMP/SETARA'), ('SMU/SETARA', 'SMU/SETARA'), ('SMK', 'SMK'), ('S1', 'S1'), ('S2', 'S2'), ('DR', 'DR'), ('PROP', 'Prof')], max_length=10)),
                ('jenis_pekerjaan', models.CharField(choices=[('Asn', 'PNS'), ('Ad', 'Angkatan Darat'), ('Au', 'Angkatan Laut'), ('Al', 'Angkatan Laut'), ('Swt', 'Swasta'), ('Pensiun', 'Pensiun')], max_length=20)),
                ('status_perkawinan', models.CharField(choices=[('BM', 'Belum menikah'), ('SM', 'Menikah'), ('JD', 'Janda'), ('DD', 'Duda')], max_length=10)),
                ('status_hub_dlm_kel', models.CharField(choices=[('KK', 'Kepala Keluarga'), ('SU', 'Suami'), ('IS', 'Istri'), ('AK', 'Anak Kandung'), ('AA', 'Anak Angkat'), ('AI', 'Anak Tiri')], max_length=30)),
                ('nama_ibu', models.CharField(max_length=50, null=True)),
                ('nama_ayah', models.CharField(max_length=50, null=True)),
                ('tempat_tinggal', models.CharField(max_length=100, null=True)),
                ('status_tempat_tinggal', models.CharField(choices=[('MILIK', 'Rumah sendiri'), ('SEWA', 'Sewa')], max_length=30, null=True)),
                ('kondisi_kesehatan', models.CharField(choices=[('B', 'Baik'), ('KB', 'Kurang baik')], max_length=30, null=True)),
                ('penyakit_khusus', models.CharField(choices=[('COVID19', 'Covid 19'), ('JTG', 'Jantung'), ('DIABET', 'Diabet'), ('ASMA', 'Asma'), ('PARU', 'Paru'), ('HIV', 'Hiv'), ('GJAL', 'Ginjal'), ('TA', 'Tidak ada')], max_length=30, null=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desa.namadesa')),
                ('kewarganegaraan', models.ManyToManyField(to='wna.WNA')),
                ('rt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rt.namart')),
                ('rw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rw.namarw')),
            ],
            options={
                'verbose_name': 'Warga',
                'verbose_name_plural': 'Warga',
            },
        ),
    ]
