# Generated by Django 3.2 on 2021-05-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='gejala_saat_terpapar',
            field=models.TextField(blank=True, help_text='Boleh dikosongkan.'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='waktu_terpapar',
            field=models.CharField(help_text='Terpapar tulis mis: 01/05/2021, Tdk terpapar tulis: -', max_length=30),
        ),
    ]
