# Generated by Django 3.2 on 2021-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_auto_20210509_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='tanggal_lahir',
            field=models.CharField(help_text='Contoh: 01/01/2001', max_length=12, null=True),
        ),
    ]
