# Generated by Django 3.2 on 2021-05-11 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_auto_20210511_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='jumlah_anggota_keluarga',
            field=models.CharField(choices=[('1 Orang', '1 orang'), ('2 Orang', '2 orang'), ('3 Orang', '3 orang'), ('4 Orang', '4 orang'), ('5 Orang', '5 orang'), ('6 Orang', '6 orang'), ('7 Orang', '7 orang'), ('8 Orang', '8 orang'), ('9 Orang', '9 orang'), ('10 Orang', '10 orang'), ('Lebih Dari 10 Orang', 'Lebih Dari 10 orang'), ('Tidak ada', 'Tidak ada')], help_text='Klik tanda panah.', max_length=30),
        ),
    ]
