# Generated by Django 3.2 on 2021-05-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_alter_warga_jumlah_anggota_keluarga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warga',
            old_name='status',
            new_name='status_perawatan',
        ),
    ]
