# Generated by Django 3.2 on 2021-05-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0001_initial'),
        ('rw', '0001_initial'),
        ('rt', '0001_initial'),
        ('warga', '0003_alter_warga_tanggal_lahir'),
    ]

    operations = [
        migrations.AddField(
            model_name='warga',
            name='covid_19',
            field=models.CharField(choices=[('TIDAK TERPAPAR', 'Tidak terpapar'), ('TERPAPAR', 'Terpapar Covid-19')], help_text='Klik tanda panah', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='warga',
            name='gejala_saat_terpapar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='warga',
            name='kondisi_kesehatan_saat_ini',
            field=models.CharField(choices=[('ISOLASI', 'Isolasi mandiri'), ('DIRAWAT', 'Dirawat di RS'), ('PULIH', 'Pulih normal')], help_text='Klik tanda panah', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='warga',
            name='waktu_terpapar',
            field=models.CharField(help_text='Contoh: 01/05/2021', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='agama',
            field=models.CharField(choices=[('Isl', 'Islam'), ('Kris', 'Kristen'), ('Kat', 'Katolik'), ('Hin', 'Hindu'), ('Kong', 'Konghucu')], help_text='Klik tanda panah', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='desa',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='desa.namadesa'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki'), ('P', 'Perem')], help_text='Klik tanda panah', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='jenis_pekerjaan',
            field=models.CharField(choices=[('Asn', 'PNS'), ('Ad', 'Angkatan Darat'), ('Au', 'Angkatan Laut'), ('Al', 'Angkatan Laut'), ('Wswt', 'Wira Swasta'), ('Pensiun', 'Pensiun')], help_text='Klik tanda panah', max_length=20),
        ),
        migrations.AlterField(
            model_name='warga',
            name='kondisi_kesehatan',
            field=models.CharField(choices=[('B', 'Baik'), ('KB', 'Kurang baik')], help_text='Klik tanda panah', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='pend_tertinggi',
            field=models.CharField(choices=[('-', 'Tidak diketahui'), ('SD', 'SD'), ('SMP/SETARA', 'SMP/SETARA'), ('SMU/SETARA', 'SMU/SETARA'), ('SMK', 'SMK'), ('S1', 'S1'), ('S2', 'S2'), ('DR', 'DR'), ('PROP', 'Prof')], help_text='Klik tanda panah', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='penyakit_khusus',
            field=models.CharField(choices=[('JTG', 'Jantung'), ('DIABET', 'Diabet'), ('ASMA', 'Asma'), ('PARU', 'Paru'), ('HIV', 'Hiv'), ('GJAL', 'Ginjal'), ('TA', 'Tidak ada')], help_text='Klik tanda panah', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='rt',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rt.namart'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='rw',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rw.namarw'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='status_hub_dlm_kel',
            field=models.CharField(choices=[('KK', 'Kepala Keluarga'), ('SU', 'Suami'), ('IS', 'Istri'), ('AK', 'Anak Kandung'), ('AA', 'Anak Angkat'), ('AI', 'Anak Tiri')], help_text='Klik tanda panah', max_length=30),
        ),
        migrations.AlterField(
            model_name='warga',
            name='status_perkawinan',
            field=models.CharField(choices=[('BM', 'Belum menikah'), ('SM', 'Menikah'), ('JD', 'Janda'), ('DD', 'Duda')], help_text='Klik tanda panah', max_length=10),
        ),
        migrations.AlterField(
            model_name='warga',
            name='status_tempat_tinggal',
            field=models.CharField(choices=[('MILIK', 'Rumah sendiri'), ('ORTU', 'Rumah orang tua'), ('SEWA', 'Sewa')], help_text='Klik tanda panah', max_length=30, null=True),
        ),
    ]
