# Generated by Django 3.2 on 2021-05-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0004_rename_status_warga_status_perawatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='hp',
            field=models.CharField(blank=True, help_text='Boleh dikosongkan.', max_length=20),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_ayah',
            field=models.CharField(blank=True, help_text='Boleh dikosongkan.', max_length=50),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_ibu',
            field=models.CharField(blank=True, help_text='Boleh dikosongkan.', max_length=50),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(help_text='Harus diisi.', max_length=100),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_panggilan',
            field=models.CharField(help_text='Harus diisi.', max_length=30),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(help_text='Harus diisi.', max_length=20),
        ),
        migrations.AlterField(
            model_name='warga',
            name='tanggal_lahir',
            field=models.CharField(blank=True, help_text='Contoh: 01/01/2001 atau Boleh dikosongkan.', max_length=12),
        ),
        migrations.AlterField(
            model_name='warga',
            name='tempat_lahir',
            field=models.CharField(blank=True, help_text='Contoh: Denpasar, Bali atau Boleh dikosongkan.', max_length=50),
        ),
    ]
