# Generated by Django 3.2 on 2021-05-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RukunTetangga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rt', models.CharField(max_length=50)),
                ('ketua', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('hp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'RT',
                'verbose_name_plural': 'RT',
            },
        ),
    ]
