# Generated by Django 3.2 on 2021-05-11 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desa', '0001_initial'),
        ('rt', '0001_initial'),
        ('rw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nama_negara_asal', models.CharField(help_text='Contoh: Amerika Serikat', max_length=30)),
                ('identitas_diri', models.CharField(max_length=10)),
                ('nomor_paspor', models.CharField(max_length=20)),
                ('masa_berlaku', models.CharField(help_text='Contoh: 01/01/2016 - 01/01/2021', max_length=30)),
                ('status_keberadaanya_di_indonesia', models.CharField(choices=[('TURIS', 'Turis'), ('BEKERJA', 'Bekerja'), ('MENIKAH', 'Menikah'), ('KUN KELUARGA', 'Kun keluarga')], max_length=30)),
                ('dokumen_lainnya', models.CharField(max_length=100, null=True)),
                ('alamat_tinggal', models.CharField(max_length=100)),
                ('catatan', models.TextField(blank=True)),
                ('desa', models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='desa.desa')),
                ('rt', models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rt.rukuntetangga')),
                ('rw', models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rw.rukunwarga')),
            ],
            options={
                'verbose_name': 'WNA',
                'verbose_name_plural': 'WNA',
            },
        ),
    ]
