# Generated by Django 3.2 on 2021-05-09 07:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nama_negara_asal', django_countries.fields.CountryField(max_length=2)),
                ('identitas_diri', models.CharField(max_length=10)),
                ('nomor_paspor', models.CharField(max_length=20)),
                ('masa_berlaku', models.CharField(help_text='01/01/2021', max_length=20)),
                ('status_keberadaanya_di_indonesia', models.CharField(choices=[('TURIS', 'Turis'), ('BEKERJA', 'Bekerja'), ('MENIKAH', 'Menikah'), ('KUN KELUARGA', 'Kun keluarga')], max_length=30)),
                ('dokumen_lainnya', models.CharField(max_length=100, null=True)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'WNA',
                'verbose_name_plural': 'WNA',
            },
        ),
    ]
