# Generated by Django 3.2 on 2021-05-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wna',
            name='nama_negara_asal',
            field=models.CharField(help_text='Contoh: Amerika Serikat', max_length=30),
        ),
    ]
