# Generated by Django 3.2 on 2021-05-09 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0001_initial'),
        ('desa', '0001_initial'),
        ('rt', '0001_initial'),
        ('wna', '0002_alter_wna_nama_negara_asal'),
    ]

    operations = [
        migrations.AddField(
            model_name='wna',
            name='alamat_tinggal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wna',
            name='desa',
            field=models.ForeignKey(blank=True, default=1, help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='desa.namadesa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wna',
            name='rt',
            field=models.ForeignKey(blank=True, default=1, help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rt.namart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wna',
            name='rw',
            field=models.ForeignKey(blank=True, default=1, help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rw.namarw'),
            preserve_default=False,
        ),
    ]
