# Generated by Django 3.2 on 2021-05-09 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rt', '0001_initial'),
        ('rw', '0001_initial'),
        ('desa', '0001_initial'),
        ('wna', '0003_auto_20210509_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wna',
            name='desa',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='desa.namadesa'),
        ),
        migrations.AlterField(
            model_name='wna',
            name='masa_berlaku',
            field=models.CharField(help_text='Contoh: 01/01/2016 - 01/01/2021', max_length=30),
        ),
        migrations.AlterField(
            model_name='wna',
            name='rt',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rt.namart'),
        ),
        migrations.AlterField(
            model_name='wna',
            name='rw',
            field=models.ForeignKey(help_text='Klik tanda panah', on_delete=django.db.models.deletion.CASCADE, to='rw.namarw'),
        ),
    ]
